version: "3.8"

services:
  pg:
    image: postgres
    container_name: pg
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    restart: always
    ports:
      - '5432:5432'

