version: "3.8"

services:
  pg:
    image: postgres
    container_name: pg
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mycontacts
    volumes:
      - ./api/src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
    ports:
      - "5432:5432"
